package data_structures_and_algorithms_in_Java_6th.chapter3_fundamental_data_structures.excercise.R_3_1;


/**
 * R-3.1 Solution
 * Give the next five pseudorandom numbers generated by the process described on
 * page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
 */
public class Solution {
}
